# Generated by Django 4.0.1 on 2022-01-31 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='interests_and_bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_bonus', models.IntegerField()),
                ('investment_interest_5days', models.IntegerField()),
                ('investment_interest_10days', models.IntegerField()),
                ('investment_interest_15days', models.IntegerField()),
                ('investment_interest_30days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invstmt_number', models.IntegerField(blank=True, unique=True)),
                ('duration', models.CharField(choices=[('1', '5 Days'), ('2', '10 Days'), ('3', '15 Days'), ('4', '30 Days')], default='1', max_length=2)),
                ('amount_in_usd', models.DecimalField(blank=True, decimal_places=2, default=65, max_digits=15)),
                ('amount_in_doge', models.DecimalField(blank=True, decimal_places=2, default=65, max_digits=15)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
