# Generated by Django 4.0.1 on 2022-01-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
