# Generated by Django 4.0.1 on 2022-02-01 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_investment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interests_and_bonus',
            old_name='investment_interest_10days',
            new_name='investment_interest',
        ),
        migrations.RemoveField(
            model_name='interests_and_bonus',
            name='investment_interest_15days',
        ),
        migrations.RemoveField(
            model_name='interests_and_bonus',
            name='investment_interest_30days',
        ),
        migrations.RemoveField(
            model_name='interests_and_bonus',
            name='investment_interest_5days',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='duration',
        ),
    ]
