# Generated by Django 4.0.1 on 2022-02-01 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_rename_investment_interest_10days_interests_and_bonus_investment_interest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='invstmt_number',
            new_name='invstmt_ref',
        ),
    ]
