# Generated by Django 4.0.1 on 2022-02-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_delete_interests_and_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='amount_in_doge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount_in_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
    ]
