# Generated by Django 3.2.12 on 2022-02-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0010_alter_investment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(blank=True, default='Processing', max_length=10),
        ),
    ]
