# Generated by Django 4.0.1 on 2022-02-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
    ]
