# Generated by Django 3.2.12 on 2022-02-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0003_rate_affiliate_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='interest_doge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='interest',
            name='interest_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='interest_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='interest',
            name='investment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
