# Generated by Django 3.2.12 on 2022-02-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0006_alter_interest_bank_total_interest_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest_bank',
            name='total_interest_coins',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
