# Generated by Django 4.0.1 on 2022-02-02 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('affiliates', '0004_alter_affiliates_benefiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliates',
            name='benefiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefiter', to=settings.AUTH_USER_MODEL),
        ),
    ]
