# Generated by Django 4.0.1 on 2022-02-02 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0005_alter_affiliates_benefiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliates',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
