# Generated by Django 4.0.1 on 2022-01-27 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_user_profile_code_user_profile_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
