# Generated by Django 4.0.1 on 2022-01-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_alter_user_profile_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='unity_number',
        ),
    ]
