# Generated by Django 4.0.1 on 2022-01-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_remove_user_profile_unity_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='id_copy',
            field=models.ImageField(blank=True, null=True, upload_to='verifications/'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='avatas/'),
        ),
    ]
