# Generated by Django 4.0.1 on 2022-01-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0006_user_profile_id_copy_alter_user_profile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='city_or_town',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='state',
        ),
    ]
